### ISSUE TITLE
issue with install: SingleCellExperiment required

### ISSUE THREAD

**Issue by jamestwebber** [ConesaLab/acorde#4] opened 2023-01-20 18:25 UTC
I was trying to install this and got the error `there is no package called ‘SingleCellExperiment’`

It looks like the package is suggested but probably should be a requirement?

**Comment by aarzalluz** [comment] 2023-01-20 19:18
Hi @jamestwebber,

Thank you for using acorde -and for bringing this to my attention.

`SingleCellExperiment` (as well as other packages such as `edgeR` or `DESeq2`) are suggested -not required- because they are only used during the multi-group DE step in the `acorde` pipeline, which is not essential to run the core parts of the method. Users may want to use a different pre-processing strategy, so this was meant to impose a minimum number of mandatory dependencies. I assume that this error arised when compiling vignettes during package installation?

Ángeles

**Comment by jamestwebber** [comment] 2023-01-20 19:29
Not as far I could tell. I just ran `> devtools::install_github("ConesaLab/acorde")` and got the following (after some dependencies):

```
The downloaded source packages are in
	‘/private/var/folders/v4/tx_h1xqj1t741r3n1zfpg_lw0000gp/T/RtmpFivhCS/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
✔  checking for file ‘/private/var/folders/v4/tx_h1xqj1t741r3n1zfpg_lw0000gp/T/RtmpFivhCS/remotesd3883049721d/ConesaLab-acorde-6d8ab0b/DESCRIPTION’ (718ms)
─  preparing ‘acorde’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘acorde’ ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
     there is no package called ‘SingleCellExperiment’
   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
   Execution halted
   ERROR: lazy loading failed for package ‘acorde’
─  removing ‘/private/var/folders/v4/tx_h1xqj1t741r3n1zfpg_lw0000gp/T/RtmpZYOMiF/Rinstd5936e1d12b8/acorde’
         -----------------------------------
   ERROR: package installation failed
```

**Comment by jamestwebber** [comment] 2023-01-20 19:31
Looks like it is getting imported: https://github.com/ConesaLab/acorde/blob/master/NAMESPACE#L24

**Comment by aarzalluz** [comment] 2023-01-20 19:48
Hi @jamestwebber -I just found the cause of the error. Turns out I added a `SingleCellExperiment` as package `data` in one of the recent updates, and forgot to update the list of dependencies accordingly. I believe it should be fixed now, please try again and let me know.

**Comment by jamestwebber** [comment] 2023-01-20 19:56
Oh I just installed the missing package to gets things to work, but I thought I'd let you know.

**Comment by aarzalluz** [comment] 2023-01-20 20:35
That's ok, thank you for reporting this -I'll close the issue now.

**Closed as completed by aarzalluz** 2023-01-20 20:35 UTC
